APP_NAME='Temanten App'
APP_ENV=$app_env
APP_KEY=
APP_DEBUG=false
APP_URL=$app_url
APP_TIMEZONE='Asia/Jakarta'

LOG_CHANNEL=stack
LOG_SLACK_WEBHOOK_URL=

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=$db_name
DB_USERNAME=$db_user
DB_PASSWORD=$db_password
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_bin

CACHE_DRIVER=file
QUEUE_CONNECTION=sync
